# 十四、异常处理

## 14.1 throw 抛异常
异常处理是指预估代码执行过程中可能发生的错误，然后最大程度的避免错误的发生导致整个程序无法继续运行

```js
function fn(x,y){
    if(!x || !y){
        throw new Error('用户没有参数传递！')
    }
    return x + y
}
console.log(fn());
```

总结:

1. throw 抛出异常信息，程序也会终止执行
2. throw 后面跟的是错误提示信息
3. Error 对象配合 throw 使用，能够设置更详细的错误信息

## 14.2 try/catch 捕获错误信息
我们可以通过try/catch捕获错误信息（浏览器提供的错误信息）try 试试 catch 拦住 finally 最后

```html
<p>123</p>
<script>
    function foo(){
        try{
            // 可能发生错误的代码 要写到 try
            const p = document.querySelector('.p')
            p.style.color = 'red'
        }catch(error){
             // 拦截错误，提示浏览器提供的错误信息，但是不中断程序的执行
             console.log(error.message);
             throw new Error('你看看，选择器错误了吧')
             // 中止代码继续执行
             // return
        }finally{
            // 不管你程序对不对，一定会执行的代码
            alert("弹出对话框")
        }
        console.log("如果出现错误，我不会执行");
    }
    foo()
</script>
```


总结

1. try...catch 用于捕获错误信息
2. 将预估可能发生错误的代码写在 try 代码段中
3. 如果 try 代码段中出现错误后，会执行 catch 代码段，并截获到错误信息
4. finally 不管是否有错误，都会执行

## 14.3 debugger

直接在代码中写入断点

打开网页开启f12 即可观察到断点

断点的作用：配合webworker 挡住其他人查看自身的网页

```js
const arr =[1,3,5]
const newArr =arr.map((item,index)=>{
    debugger    
    console.log(item)   // 当前元素
    console.log(index)  // 当前元素索引号
    return item+10  //让当前元素+10
})
console.log(newArr) //[11,13，15]
```